### ISSUE TITLE
Install problem, ascii codec can't decode byte

### ISSUE THREAD

**Issue by ways** [coding-world/max7219#1]
```
pi@led01:~/max7219-master $ sudo python3 setup.py --install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    README = open(os.path.join(os.path.dirname(__file__), 'README.rst')).read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4704: ordinal not in range(128)
```

This is on a Pi

$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by ways** [comment]
Never mind. My locale was wrong.
